package com.swentseekr.seekr.ui.review

/** Constants used in ReviewHuntViewModel unit tests. */
object ReviewHuntViewModelTestConstantsStrings {
  const val TEST_HUNT_ID = "hunt123"
  const val START_LABEL = "Start"
  const val END_LABEL = "End"
  const val HUNT_TITLE = "Test Hunt"
  const val HUNT_DESCRIPTION = "Test Description"
  const val AUTHOR_ID = "author123"
  const val IMAGE_URL = ""
  const val ERROR_MESSAGE_WRONG = "Something went wrong"
  const val EMPTY_REVIEW_MESSAGE = ""
  const val REVIEW_EMPTY_ERROR_MESSAGE = "The review cannot be empty"
  const val REVIEW_MESSAGE_GOOD = "Nice hunt!"
  const val RATING_ERROR_MESSAGE = "Rating must be between 1 and 5"
  const val FAILED_GET_REVIEW_MESSAGE = "Failed to get review"
  const val REVIEW_ID = "review123"
  const val USER_ID = "user123"

  const val FAKE_USER_ID = "testUser"
  const val PHOTO_NAME = "test_photo.jpg"
  const val INPUT_PHOTO_PATH = "somepath/image.jpg"
  const val LOCAL_PHOTO_PATH = "local://review_image/user123"
  const val UPLOAD_PHOTO_ERROR = "Upload failed"
  const val MY_PHOTO = "file://somephoto.jpg"
  const val FAILED_UPLOAD_PHOTO_MESSAGE = "Failed to upload photo: Upload failed"
  const val ANOTHER_PHOTO = "photo_to_remove.jpg"
  const val DELETE_PHOTO_ERROR = "Delete failed"
  const val PHOTO_TO_FAIL = "photo_to_fail.jpg"
  const val FAILED_DELETE_PHOTO_MESSAGE = "Failed to delete image: Delete failed"
  const val INVALID_SUBMISSION_MESSAGE = "At least one field is not valid"
  const val EMPTY = ""
  const val REVIEW_MESSAGE_1 = "Great hunt!"
  const val REVIEW_MESSAGE_3 = "Amazing!"
  const val REVIEW_MESSAGE_4 = "Nice!"
  const val ERROR_SUBMISSION = "Cannot clear form, review not submitted successfully."
  const val OTHER_USER_ID = "otherUser456"
  const val DELETE_REVIEW_FORBIDDEN_MESSAGE = "You can only delete your own review."
  const val FAIL_CANCEL = "Failed to cancel image selection. Simulated failure"
}
