package com.swentseekr.seekr.ui.review

object ReviewHuntViewModelTestConstantsStrings {
  const val TestHuntId = "hunt123"
  const val Start = "Start"
  const val End = "End"
  const val HuntTitle = "Test Hunt"
  const val HuntDescription = "Test Description"
  const val AuthorId = "author123"
  const val ImageURL = ""
  const val ErrorWrong = "Something went wrong"
  const val ReviewMsg = ""
  const val ReviewErrorMsg = "The review cannot be empty"
  const val ReviewMessageGood = "Nice hunt!"
  const val RatingErrorMsg = "Rating must be between 1 and 5"
  const val FailGetReview = "Failed to get review"
  const val ReviewId = "review123"
  const val UserId = "user123"

  const val FakeUserId = "testUser"
  const val Photo = "test_photo.jpg"
  const val InputPhoto = "somepath/image.jpg"
  const val Path = "local://review_image/user123"
  const val UploadPhotoFail = "Upload failed"
  const val MyPhoto = "file://somephoto.jpg"
  const val FailUplaodPhotoTest = "Failed to upload photo: Upload failed"
  const val AnotherPhoto = "photo_to_remove.jpg"
  const val DeletePhotoFail = "Delete failed"
  const val FailPhoto = "photo_to_fail.jpg"
  const val FailDeletePhotoTest = "Failed to delete image: Delete failed"
  const val NotValidSubmission = "At least one field is not valid"
  const val Empty = ""
  const val ReviewMsg2 = "Great hunt!"
  const val ReviewMsg3 = "Amazing!"
  const val ReviewMsg4 = "Nice!"
  const val ErrorSubmission = "Cannot clear form, review not submitted successfully."
  const val OtherUserId = "otherUser456"
  const val FailDeleteReview = "You can only delete your own review."
  const val FailCancle = "Failed to cancel image selection. Simulated failure"
}
